### ISSUE TITLE
dsmcInitialise

### ISSUE THREAD

**Issue by ghost** [Eliasfarah0/dsmcFoamPlus-case-setup-for-the-2D-Orion-Crew-Module#1]
After fixing the "internalDegreesOfFreedom"issue on constant/dsmcProperties, I found an issue related to the temperature definition that I could not solve.   
--> FOAM FATAL IO ERROR: (openfoam-2012)
Entry 'temperature' not found in dictionary "/home..."

**Comment by Eliasfarah0** [comment]
According to your Error: --> FOAM FATAL IO ERROR: (openfoam-2012)
You have a different OpenFOAM built version which is OpenFOAM ESI version (v2012). Follow the readme.md file, to install the correct OpenFOAM foundation version (v2.4.0).
